# Generated by Django 2.2.6 on 2022-09-08 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20220908_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whovoted',
            name='post',
        ),
        migrations.AddField(
            model_name='whovoted',
            name='post_id',
            field=models.IntegerField(default=None),
        ),
    ]
