# Generated by Django 2.2.6 on 2022-09-08 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20220908_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='whovoted',
            name='type',
            field=models.TextField(default=None),
        ),
    ]
