# Generated by Django 2.2.16 on 2024-02-12 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_auto_20221014_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhoVoted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(null=True)),
                ('post_id', models.IntegerField(null=True)),
                ('type', models.TextField(null=True)),
            ],
        ),
    ]
